### ISSUE TITLE
[Beta 1.5f] Altagrave and Altagrave (C) cause CTD in fleet/refit view.

### ISSUE THREAD

**Issue by CloudOfNeutronFlux** [gomarz/SS-armaa#1]
Log below. 
[starsector.log](https://github.com/gomarz/SS-armaa/files/7017369/starsector.log)

(G) and (EX) seem to be fine.

**Comment by gomarz** [comment]
Graphicslib is a dependency once again, enabling should resolve.

**Comment by CloudOfNeutronFlux** [comment]
Don't forget to include it in the mod_info thing! <3
