### ISSUE TITLE
[Beta 1.5.1] Is it possible to change WINGCOM SUITE fighters' spawnpoint at the beginning of a fight?

### ISSUE THREAD

**Issue by CloudOfNeutronFlux** [gomarz/SS-armaa#10]
Currently, they spawn at the edge of the map, even if there is a carrier present at the start of a battle, and it takes a noticeable amount of time for them to catch up to the main forces (especially in smaller skirmishes where you spawn closer to the center of the map).

**Comment by gomarz** [comment]
Adjusted
- If Carriers are present,  fighters will deploy from one instead of edge of the map and set it as their home carrier to refit at
- If not, original behavior is used
