### ISSUE TITLE
[Beta 1.5.1] Strikecraft only follow orders when the command screen is open.

### ISSUE THREAD

**Issue by CloudOfNeutronFlux** [gomarz/SS-armaa#15]
Video below.
https://youtu.be/2ts2e2Hzul8

**Comment by gomarz** [comment]
Orders work but fighter hullsize can't interact with objectives. May not be fixable (at least cleanly..?)
May be able to just swap hullsize when near objective

**Comment by gomarz** [comment]
Doesn't seem to have a simple solution per alex, will look into other options

**Comment by gomarz** [comment]
Strikecraft will automatically have any orders to capture/assault objectives cancelled with a notification as to why. Seems to be working, for now
