### ISSUE TITLE
Multiple case-mismatched graphics files

### ISSUE THREAD

**Issue by Beinsezii** [gomarz/SS-armaa#16]
There's multiple misnamed files in the new ships that prevent the game from booting on any install with a case-sensitive filesystem, aka everything outside of the Windows-verse

The files present are:
```
 * graphics/armaa/ships/leynos/armaa_leynos_hips.png
 * graphics/armaa/ships/leynos/armaa_leynos_hips_glow1.png
 * graphics/armaa/ships/leynos/armaa_leynos_hips_glow2.png
 * graphics/armaa/weapons/armaa_valkencustomGun.png
```
Meanwhile, the mod checks for the following:
```
 * graphics/armaa/ships/leynos/armaa_leynos_Hips.png
 * graphics/armaa/ships/leynos/armaa_leynos_Hips_glow1.png
 * graphics/armaa/ships/leynos/armaa_leynos_Hips_glow2.png
 * graphics/armaa/weapons/armaa_valkencustomgun.png
```

For some cases, the code checks for *both* variants, so the only user-end solution is to either duplicate or link the files to new names.

Simple solution would be to just "audit" (regex search) for the offending file calls and change them to match the physical files.

Going forward, it'd be a good idea to exclusively use snake_case or camelCase to avoid future problems.

**Comment by gomarz** [comment]
adjusted filenames, should be good now.
