### ISSUE TITLE
[1.5.2] Moonlight issues

### ISSUE THREAD

**Issue by CloudOfNeutronFlux** [gomarz/SS-armaa#17]
I installed a bunch of range extending mods on Aleste (Advanced Optics, Dampened Mounts, ITU), and it seems like Moonlight blades start behaving weirdly once they get past their normal range. The beam of the weapon extends too slowly to reach its full length in the first half of the animation, and this leads to AI being unable to hit its target even though it's technically within weapon range.

Another thing I noticed is that this issue can be sort of mitigated by *speeding up the game* using the SpeedUp mod. I don't know if this is something specific to Moonlights or just a vanilla quirk, but it's there.

Video with examples of above:
https://youtu.be/d7FFDaqoxsU

**Comment by CloudOfNeutronFlux** [comment]
I've been told that the second issue is because of SpeedUp itself, so disregard that one.

**Comment by gomarz** [comment]
AHHHHHH
