### ISSUE TITLE
[1.5.2] The bullet time effect of Einhander's phase system disappears after any non-flagship cataphract is destroyed.

### ISSUE THREAD

**Issue by CloudOfNeutronFlux** [gomarz/SS-armaa#19]
The effect is gone for the rest of the battle.

Video for demonstration below:
https://youtu.be/6KbGNq2x6LU

**Comment by gomarz** [comment]
Wasn't able to reproduce in-dev, though the current version has Einhander using traditional Phase Cloak, so its current system may be the issue.

**Comment by CloudOfNeutronFlux** [comment]
Noticed this issue happening to other ships with bullet time effects (phase cloak, temporal shell, etc.) as well. I'll try getting more details on this in a few days.

**Comment by gomarz** [comment]
closing for now since it doesn't seem to be isolated to armaa
