### ISSUE TITLE
[1.95 pre-release] RCL-48 Recoilless Rifle is refusing to target enemy cataphracts

### ISSUE THREAD

**Issue by CloudOfNeutronFlux** [gomarz/SS-armaa#35]
Initially thought it wasn't firing 'cause the AI was having trouble calculating trajectories due to slow projectile speed, but testing it against nimble frigates proved otherwise.

**Comment by gomarz** [comment]
They aren't targetted since they're classed as fighters and the weapon is a STRIKE weapon + USE_VS_FRIGATES
