### ISSUE TITLE
[v2.1.2c pre-release] VX Custom's midline skin has too many things going on in it.

### ISSUE THREAD

**Issue by CloudOfNeutronFlux** [gomarz/SS-armaa#48]
Highly subjective and maybe it's just me, however it seems like there are too many colors, especially compared to AASV and Comet skins; you got midline yellow contrasted by a much darker faintly yellow-ish grey on the body and V-azard's classic grey-brown and red legs. My eyes get lost a bit among all these.

![image](https://user-images.githubusercontent.com/85829719/195452428-5d0c65fe-e33f-439f-8aaa-d612c8b48718.png)

**Comment by gomarz** [comment]
The hue is off for the legs, but imo midline legs look worse. I'll darken the legs
![image](https://user-images.githubusercontent.com/12466772/195482547-ffb4e47d-7237-4c12-b601-393765f37f8b.png)

For nw, ill programatically tweak the legs to minimize the reddish hue.
![image](https://user-images.githubusercontent.com/12466772/195483938-248e7d33-d0ef-4d0e-bc29-a401004552a2.png)

**Comment by CloudOfNeutronFlux** [comment]
Ooh, that redless variant is onto somthing. Maybe if the grey on the torso is spread out a bit more so it isn't only on the front plate (with a smidge behind the head)?
