### ISSUE TITLE
[2.1.3] OVERLORD SUITE [ALPHA] doesn't use (and doesn't need) an alpha core.

### ISSUE THREAD

**Issue by CloudOfNeutronFlux** [gomarz/SS-armaa#52]
You can add the mod regardless if you have one in your inventory and/or storage.

**Comment by gomarz** [comment]
Looks like it does consume cores but only after time advances in the campaign layer (I.E equip, exit to campaign layer, core is consumed) will ook int correcting that

**Comment by gomarz** [comment]
fix'd
