### ISSUE TITLE
[2.1.3] OVERLORD SUITE [BETA] and OVERLORD SUITE [GAMMA] can't be installed.

### ISSUE THREAD

**Issue by CloudOfNeutronFlux** [gomarz/SS-armaa#53]
![image](https://user-images.githubusercontent.com/85829719/198210332-714d1639-afa0-42e3-8880-0dbf62922866.png)
![JS7OSQrNZo](https://user-images.githubusercontent.com/85829719/198210790-3f751324-5eba-415e-8694-70b6d4e568d6.png)

**Comment by gomarz** [comment]
I somehow made the hullmods incompatible with themselves. wow

**Comment by gomarz** [comment]
fix'd
