### ISSUE TITLE
3.0 release naming schemes are incorrect

### ISSUE THREAD

**Issue by UrAverageDavid** [gomarz/SS-armaa#61]
Until now, I was able to find 2 cases of this error occuring:

- The game requests hazardleftShoulder, but the file itself is named hazardLeftShoulder, causing a crash while the game is loading
- The karma system's burst feature is named armaa_karma_pulse in the mod files, but the game still request armaa_karmicburst, which was the name of this spec in the previous version of the mod.

I'll try to add more as I go.

**Comment by gomarz** [comment]
Thanks for the report! I pushed a hotfix directly to 3.0. and added back armaa_karmicburst, and the naming error should now be fixed
